name       : glow
version    : 1.2.1
release    : 1
homepage   : https://github.com/charmbracelet/glow
source     :
    - https://github.com/charmbracelet/glow/archive/v1.2.1.tar.gz : ceb9369e2f93412abf914fd4cdc2e1a7e70cf48e2b2607c1e10847223c4a1b68
license    : MIT
component  : office.notes
summary    : Glow is a terminal based markdown reader designed from the ground up to bring out the beauty—and power—of the CLI.
description: |
    Glow is a terminal based markdown reader designed from the ground up to bring out the beauty—and power—of the CLI. Use it to discover markdown files, read documentation directly on the command line and stash markdown files to your own private collection so you can read them anywhere. Glow will find local markdown files in subdirectories or a local Git repository.
networking : yes
extract    : no
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p src/github.com/charmbracelet/glow
    tar xf $sources/v${version}.tar.gz -C src/github.com/charmbracelet/glow --strip-components 1
build      : |
    cd ..
    export GOPATH=`pwd`
    export GO111MODULE=on
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/charmbracelet/glow
    %make
install    : |
    cd src/github.com/charmbracelet/glow/
    install -Dm00755 glow $installdir/usr/bin/glow
